name: TradieConnectCICD

on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Step  3 - Build Maven project
        run: mvn -B package --file backend/pom.xml
      
      - name: Step 4 - List Directory
        run: ls -a
        
      - name: Step  5 - Target Folder
        run: 
          cd target
          ls -a
          
          
      
